// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:14c18902-8f64-4108-a6ac-65891e1f6eef",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_b87m1L5qj",
    "aws_user_pools_web_client_id": "1deu3bnp56sc2f8qcedus6r8ji",
    "oauth": {}
};


export default awsmobile;
