# This file describes AWS Resources and is specifically written in a way to be included in
# a serverless.yml file. By itself it is not a valid CloudFormation template.

Resources:
    
  ClinGenTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: 'PK'
          AttributeType: 'S'
        - AttributeName: 'item_type'
          AttributeType: 'S'
        - AttributeName: 'clinvarVariantId'
          AttributeType: 'S'
        - AttributeName: 'carId'
          AttributeType: 'S'
        - AttributeName: 'last_modified'
          AttributeType: 'S'
        - AttributeName: 'affiliation'
          AttributeType: 'S'
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        -
          AttributeName: 'PK'
          KeyType: HASH
      TableName: ${self:custom.resources.gci-vci-table-name}
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      GlobalSecondaryIndexes:
      - IndexName: item_type_index
        KeySchema:
        - AttributeName: item_type
          KeyType: HASH
        - AttributeName: last_modified
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
      - IndexName: clinvarVariantId_index
        KeySchema:
        - AttributeName: clinvarVariantId
          KeyType: HASH
        Projection:
          NonKeyAttributes:
          - rid
          - carId
          ProjectionType: INCLUDE
      - IndexName: carId_index
        KeySchema:
        - AttributeName: carId
          KeyType: HASH
        Projection:
          NonKeyAttributes:
          - rid
          - clinvarVariantId
          ProjectionType: INCLUDE
      - IndexName: affiliation_index
        KeySchema:
        - AttributeName: affiliation
          KeyType: HASH
        - AttributeName: last_modified
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
          